language: c

compiler:
    - gcc
    - clang

script:
    - ./bootstrap
    - ./configure
    - make
    - ./configure --disable-crc32chw
    - make clean && make
    - ./configure --disable-shared --enable-static
    - make clean && make
